baseURL = "http://robbiesri.github.io"
languageCode = "en-us"
title = "Graphics y Cooking"
theme = "erblog"

footnoteReturnLinkContents = "^"

[params]
    author = "Rob Srinivasiah"
    description = "LFG"
    portrait = "site_content/mom_rob.JPG"
    google_search = true
    bio = """
    <p> This is a graphics programming and cooking blog. </p>
    <p> The most classicest of combos. </p>
    """

[taxonomies]
    cooking-style = "cooking-styles"
    graphics-area = "graphics-areas"

[[menu.icon]]
    name = "github"
    url = "https://github.com/robbiesri/"
    weight = 1

[[menu.icon]]
    name = "twitter"
    url = "https://twitter.com/RobbieSri"
    weight = 1

[[menu.icon]]
    name = "envelope-square"
    url = "mailto:rob@robds.net"
    weight = 1

[[menu.icon]]
    name = "instagram"
    url = "https://www.instagram.com/dj_robbies/"
    weight = 1
